### ISSUE TITLE
"! Undefined control sequence" error

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#10]
Improper TeX output is being generated for the attached DOCX file .

Overfull \hbox (18.6093pt too wide) in paragraph at lines 65--66
\OT1/cmr/m/n/10.95 ovial-sarkome. Die h^^?aufigsten We-ichteil-sarkome des Erwa
ch-se-nen sind in Tabelle 1 aufgef^^?uhrt.
[4] (/opt/local/share/texmf-texlive/tex/latex/base/omlcmr.fd) [5] [6]
Chapter 3.
! Undefined control sequence.
l.74 ... 3-gradige Klassifikationsschema der {\grq
                                                  }French Federation of Canc...

**Comment by lwittmar** [comment]
the latex babel package, where \grq is defined, was missing in the default configuration. should be working after a "git pull"
