### ISSUE TITLE
Unparseable command line argument: 'to'.

### ISSUE THREAD

**Issue by XtrumE** [transpect/docx2tex#105]
Hello!

On Win11 running d2t.bat the error "Unparseable command line argument: 'to'." occurs. 

The log says further: 

> "Usage: com.xmlcalabash.drivers.Main [switches/options] [pipeline.xpl] [options]

> or: com.xmlcalabash.drivers.Main [switches/options] { [inputs/parameters] step [options] }+"

What can I do to fix this?

**Comment by gimsieke** [comment]
Can you give your whole invocation line and also the full path of the directory from which you invoke it? In addition, the output of `java -version`, please.

You can try to invoke it from a directory that has no space or special characters, and also avoid these characters in the file name.

Maybe related to #81 and #82.

**Comment by XtrumE** [comment]
The docx2tex directory is located in C:/ and the file that I want to convert is in C:/docx2tex. 

I tried:
>C:\docx2tex>d2t.bat "01 Technik.docx"

After that, the terminal showed the following messages:

> starting docx2tex
> [info] Unzipping: C:/docx2tex/01 Technik.docx ==> C:/docx2tex/01 Technik.docx.tmp\
> [info] Unzipped 40 files
> [info] Unzip finished successfully.
> Errors encountered while running docx2tex. Please see C:/docx2tex/01 Technik.log for details.

The log says:
>[main] ERROR com.xmlcalabash.drivers.Main - Pipeline failed: Internal error evaluating template rule  at line 627 in module file:/C:/docx2tex/docx2hub/xsl/wml2dbk.xsl
>[main] ERROR com.xmlcalabash.drivers.Main - Underlying exception: Cannot invoke "java.io.Reader.read(char[], int, int)" because "reader" is null

C:\docx2tex>java -version outputs:
>java version "21.0.2" 2024-01-16 LTS
>Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
>Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

**Comment by mkraetke** [comment]
Did you tried to replace the whitespace with an underscore in the filename? Does this work?

**Comment by XtrumE** [comment]
> Did you tried to replace the whitespace with an underscore in the filename? Does this work?

Yes, I tried again with the file named "01.docx". However, the errors still occur.

**Comment by gimsieke** [comment]
Can you send us the Word file? You can email it to letexml@le-tex.de

**Comment by gimsieke** [comment]
This is an error that is caused by Calabash 1.5.7. I addressed this error only in our mirror of the Calabash/Saxon10 repo, https://subversion.le-tex.de/common/github-mirror/calabash_saxon_10/, by reverting to Calabash 1.4.1.

I fixed another bug only in the mirror: Saxon 10.8 that was bundled had another issue, therefore I reverted to Saxon 10.7 (disguised as Saxon-HE-10.8.jar because the Calabash distro apparently has the jar name baked into it).

The relevant commits are r11405 for the Saxon jar and r10707 for the Calabash downgrade (plus today’s r11791 for calabash.bat because I forgot to refer to Calabash 1.4.1 instead of 1.5.7 in calabash.bat – we usually pay more attention to calabash.sh; calabash.bat often comes second wrt testing or bug fixing):

```
gerrit@Ada:~/w/Dev/tmp/docx2tex$ svn log -l9 https://subversion.le-tex.de/common/github-mirror/calabash_saxon_10/
------------------------------------------------------------------------
r11791 | gimsieke | 2024-02-17 10:12:14 +0100 (Sat, 17 Feb 2024) | 1 line

reflect downgrade to Calabash 1.4.1 due to 'java.io.Reader.read' error as reported in https://github.com/transpect/docx2tex/issues/105
------------------------------------------------------------------------
r11734 | gimsieke | 2024-02-13 15:17:33 +0100 (Tue, 13 Feb 2024) | 1 line

sync a bit with https://www.w3.org/TR/xproc/schemas/xproc.rng and https://www.w3.org/TR/xproc/schemas/steps.rng (wrapper-prefix etc.)
------------------------------------------------------------------------
r11632 | gimsieke | 2024-01-31 15:57:21 +0100 (Wed, 31 Jan 2024) | 1 line

commons-imaging-1.0-alpha3 in the classpath for image-props-extension
------------------------------------------------------------------------
r11405 | gimsieke | 2024-01-09 17:40:37 +0100 (Tue, 09 Jan 2024) | 1 line

Saxon HE 10.7 disguised as 10.8 because a 'Cannot copy a variable reference whose binding is unknown' (https://saxonica.plan.io/issues/4886) seems to reappear in 10.8
------------------------------------------------------------------------
r11404 | mkraetke | 2024-01-09 17:01:17 +0100 (Tue, 09 Jan 2024) | 1 line

catch exception because of buggy eps files
------------------------------------------------------------------------
r11402 | mkraetke | 2024-01-09 13:41:58 +0100 (Tue, 09 Jan 2024) | 1 line

revert to commons-imaging-1.0-alpha2 because of issues with eps files
------------------------------------------------------------------------
r11393 | ciuser | 2024-01-08 16:51:08 +0100 (Mon, 08 Jan 2024) | 1 line

fix classpath of image transform extension
------------------------------------------------------------------------
r10814 | fr4nze | 2023-11-07 16:21:22 +0100 (Tue, 07 Nov 2023) | 1 line

added row- and columnspacing for mtables
------------------------------------------------------------------------
r10707 | gimsieke | 2023-10-09 12:07:59 +0200 (Mon, 09 Oct 2023) | 1 line

revert to 1.4.1 and related http libs because there was 'java.lang.NullPointerException: Cannot invoke java.io.Reader.read(char[], int, int) because reader is null' when using unparsed-text()
------------------------------------------------------------------------
```

@mkraetke, you can either use the mirror or we can downgrade our calabash repos on Github to reflect the downgrades to Calabash and Saxon that I did in the mirror.

Calabash 1.5.7 is the most recent version on https://github.com/ndw/xmlcalabash1/releases

@XtrumE, may we forward the docx that you sent us to Norman Walsh so that he may look into the issue? I’d file a Calabash issue then. But a fix might take a long time. 

For the time being, I don’t see an alternative to the downgrades that I did in the mirror repo, either by using the mirror repo itself or by applying them to the Github repo, too.

@XtrumE, if you need a quick fix and if you have an svn client, you can delete the calabash directory in docx2tex and instead

```
svn co https://subversion.le-tex.de/common/github-mirror/calabash_saxon_10/ calabash
```

**Comment by mkraetke** [comment]
Hi @XtrumE,

I've downgraded Calabash from 1.5.7 to 1.4.1. Please update to the latest version and confirm whether this resolves the issue.

Best, Martin

**Comment by XtrumE** [comment]
Hi @gimsieke and @mkraetke,

Thanks for your efforts. @gimsieke, please feel free to forward the file. I'd appreciate a solution in Calabash.

I have now updated to the latest version with the downgraded Calabash using git (I don't use svn at the moment). The error now does not occur anymore. But, I am afraid that another Calabash error arose. The log says:

> '1.5.@setlocal' is not recognized as an internal or external command,
> operable program or batch file.
> [main] ERROR com.xmlcalabash.drivers.Main - java.lang.ClassNotFoundException: org.xmlresolver.Resolver
> [main] ERROR com.xmlcalabash.drivers.Main - Underlying exception: org.xmlresolver.Resolver

So, I need your help once more.

Best wishes!

**Comment by XtrumE** [comment]
... one additional remark: I have now tried it using an Ubuntu VM where it worked perfectly!

**Comment by gimsieke** [comment]
Martin prepended the '1.5.' to the line by accident I guess. I removed it [in the master branch](https://github.com/transpect/calabash-frontend/blob/master/calabash.bat).

**Comment by mkraetke** [comment]
The line was reintroduced because of the downgrade mentioned above. Perhaps these mirrors should be also synced with our GitHub mirror to avoid these issues.

**Comment by MelchiorUU** [comment]
Reverted to the initial 1.9 release (https://github.com/transpect/docx2tex/releases/tag/v.1.9) and everything works fine. Tried this as the errors seemed to have to do with Saxon or Calabash versions being too old. 

Maybe trying to fix this issue made it worse? :P

**Comment by mkraetke** [comment]
While cloning the repository, do you added `--recursive` so that the Git submodules are checked out as well?

```bash
$ git clone https://github.com/transpect/docx2tex --recursive
```

**Comment by MelchiorUU** [comment]
Yes, I did exactly as the documentation stated on the initial installation. Did the same for reverting to the January release.

**Comment by MelchiorUU** [comment]
Used Master and that seems to work without errors now.
