### ISSUE TITLE
! LaTeX Error: Lonely \item--perhaps a missing list environment.

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#11]
I am receiving the following error for a given DOCX document (sorry, I can not provide the source
due to non-disclosure reasons).

Package hyperref Warning: Suppressing link with empty target on input line 59.

Package hyperref Warning: Suppressing link with empty target on input line 61.

! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.61 		\href{}{1.1}\item \href
                              {}{Besondere Darstellungen im Handbuch	}

  58
  59 \href{}{1.  Aufbau des Handbuchs    }
  60
  61         \href{}{1.1}\item \href{}{Besondere Darstellungen im Handbuch   }
  62
  63         \href{}{1.2}\item \href{}{Zielgruppe    }
  64
  65         \href{}{1.3}\item \href{}{Die Themenabschnitte des Handbuchs im \"{U}berblick   }

**Comment by mkraetke** [comment]
Thank you for your report. It seems to me that there is a headline format, which is not defined. docx2tex considers this as list item because of the leading number. I'll figure out how to prevent this behaviour.

**Comment by gimsieke** [comment]
Is this fixed now?

**Comment by mkraetke** [comment]
I'm quite unsure which release fixed the problem, but it is fixed now.
