### ISSUE TITLE
ERROR: An empty sequence is not allowed as the result of function tr:theme-font()

### ISSUE THREAD

**Issue by davidonlaptop** [transpect/docx2tex#15]
Hi guys,

I am having this issue. Does this sounds familiar to you?
```
./d2t -o tmpp ~/workspace/ets/phd/thesis/versions/v1.11.docx
starting docx2tex
Errors encountered while running docx2tex. Please see /Users/david/opt/docx2tex/tmpp/v1.11.d2t.log for details.
```

Log file:
```
Message: Mode: insert-xpath
ERROR: file:/Users/david/opt/docx2tex/docx2hub/xsl/insert-xpath.xsl:223:err:XTTE0780:An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: An empty sequence is not allowed as the result of function tr:theme-font()
ERROR:     cause: file:/Users/david/opt/docx2tex/docx2hub/xsl/insert-xpath.xsl:223:err:XTTE0780:An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: An empty sequence is not allowed as the result of function tr:theme-font()
ERROR:     cause: file:/Users/david/opt/docx2tex/docx2hub/xsl/insert-xpath.xsl:223:err:XTTE0780:An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: An empty sequence is not allowed as the result of function tr:theme-font()
ERROR:     cause: file:/Users/david/opt/docx2tex/docx2hub/xsl/insert-xpath.xsl:223:err:XTTE0780:An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: An empty sequence is not allowed as the result of function tr:theme-font()
ERROR:     cause: file:/Users/david/opt/docx2tex/docx2hub/xsl/insert-xpath.xsl:223:err:XTTE0780:An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: Pipeline failed: An empty sequence is not allowed as the result of function tr:theme-font()
ERROR: Underlying exception: An empty sequence is not allowed as the result of function tr:theme-font()
```

I am using the master branch.

In fact I don't really care about the system font. I don't if there is way to ignore this error and continue?

**Comment by gimsieke** [comment]
Hi David,

Thanks for reporting this. This particular error doesn’t sound familiar, but we’ll know how to fix it. Fixing it will be easier if you send us your file. If you don’t want to disclose the content, you can try to delete it first, then try whether the issue may still be reproduced. You can send the file to letexml@le-tex.de.

Gerrit

**Comment by davidonlaptop** [comment]
Hi Gerrit,

Thanks for your prompt feedback. I'll be sending you the file shortly.

-D

**Comment by gimsieke** [comment]
I fixed this, but there’s other unexpected internal structure in the docx file. Now looking at the tables… 
The table of contents is an actual table, for ex., or rather, multiple tables. This is probably due to the PDF provenance. But never mind, dealing with this uncommon internal markup will only harden the converter and make it applicable more universally.

**Comment by gimsieke** [comment]
Try checking out the most recent version:
```
git clone https://github.com/transpect/docx2tex --recursive
```
or if you already used the cloned repo instead of the zip:
```
git pull
git submodule foreach git pull origin master
```
or [maybe alternatively](http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules#answer-8084186)
```
git pull --recurse-submodules
```
(not 100% sure whether this will really update all that is needed – I’m no git expert, I’m too dumb for git)

**Comment by gimsieke** [comment]
Another hint: You mentioned (in the mail message) that you used http://pdf2docx.com/ to convert a PDF to docx. The docx tables in the output lack the `w:tblGrid` element from which we are reading column counts and column widths. I now implemented a fallback for when this information is missing. This fallback might break if there are multi-column or multi-row table cells. It is probably safest to open the resulting docx with either Word 2007 (or newer) or LibreOffice 5.

**Comment by davidonlaptop** [comment]
Thanks @gimsieke . The decompilation works now!
