### ISSUE TITLE
Improper LaTeX output

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#2]
docx2text running on 

http://public.zopyx.com/lungenkarzinom-nicht-kleinzellig-nsclc.docx

generates improper LaTeX....possibly an improper DOCX structure however the converter should
perhaps not generate improper output but add some logging message to the log.

--------

[Loading MPS to PDF converter (version 2006.09.02).]
) (/opt/local/share/texmf-texlive/tex/latex/oberdiek/epstopdf-base.sty
(/opt/local/share/texmf-texlive/tex/latex/oberdiek/grfext.sty)
(/opt/local/share/texmf-texlive/tex/latex/latexconfig/epstopdf-sys.cfg))
(/opt/local/share/texmf-texlive/tex/latex/hyperref/nameref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/gettitlestring.sty))
[1{/opt/local/var/db/texmf/fonts/map/pdftex/updmap/pdftex.map}] [2]
Chapter 1.

! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.29 2.\item \chapter
                     {Grundlagen}
? c
Type <return> to proceed, S to scroll future error messages,
R to run without stopping, Q to run quietly,
I to insert something, E to edit your file,
1 or ... or 9 to ignore the next 1 to 9 tokens of input,
H for help, X to quit.

**Comment by mkraetke** [comment]
The bug is caused by our list module. More precisely, the module detects a list item by its indent and applies wrapper elements. This behaviour is generally desired, except for headlines. I will filter any XPath context which is considered for a section or chapter by configuration.

**Comment by mkraetke** [comment]
I think I resolved the issue. When a user configure an XML node to become a LaTeX section or a chapter, then css:text-indent and css:margin-left are removed from these nodes. This prevents the list generator to apply list styles on this nodes if they have such styles.
