### ISSUE TITLE
doc2tex throws an error while running it in Windows

### ISSUE THREAD

**Issue by chinnaGuggilla** [transpect/docx2tex#21]
Following is the error I get when I run it in Windows 10 using this command  
d2t.bat filename.docx

ERROR: There is a binding for the port 'conf' but the pipeline declares no such port.

**Comment by mkraetke** [comment]
Thank you for the report. I've changed the invocation in the Batch file and now it should work for you. The changes are active with commit e5c446201f032e46266cb70c8c3ee2d02d2f94a5.

**Comment by chinnaGuggilla** [comment]
Dear Martin Kraetke,

             Thanks for your quick reply. It works.

Best,
Chinnappa Guggilla

**Comment by rishinair** [comment]
I get the same error. I am using the 1.6 version (Linux/Ubuntu 16.04):

ERROR: There is a binding for the port 'conf' but the pipeline declares no such port.

**Comment by gimsieke** [comment]
I haven’t tried it, but the pipeline seems to expect the [conf file as an option](https://github.com/transpect/docx2tex/blob/master/xpl/docx2tex.xpl#L38). So you can try

```
calabash/calabash.sh -o result=myfile.tex -o hub=myfile.xml xpl/docx2tex.xpl docx=test.docx conf=conf/conf.xml 
```

If this works, we need to update [the readme](https://github.com/transpect/docx2tex/blob/master/README.md) accordingly.

**Comment by rishinair** [comment]
This works perfectly well. Thank you so much for the swift support.
