### ISSUE TITLE
soft hypen tranlated into " 

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#22]
I've added 
```xml
    < !-- soft hyphen -->
    <char character="&#xAD;" string="\-"/>
```

in conf.xml on l.613
and now the translation seems good

Please find a MWE here:
https://medialab.sissa.it/owncloud/index.php/s/9v5oRQ48oXZnZv8

P.S. I've just started using docx2tex and it seems very very good. Thanks a lot :-)

**Comment by gamboz** [comment]
oops, just saw now l.647 in conf.xml
I think it might be wrong and it should be replaced with the one above

**Comment by gimsieke** [comment]
It seems as if the current conf.xml assumes that the [babel package with `ngerman` shortcuts](https://tex.stackexchange.com/questions/27198/babel-adding-ngerman-s-language-shorthands-to-english-as-the-main-document-lan) is active.
Yes, we should not assume that this package is active, and we should revert to standard LaTeX markup here.

**Comment by mkraetke** [comment]
Hi @gamboz, thank you very much for your report. I've replaced the soft hyphen in commit fa2318b8d160a08c200d07da9d11fe103afb62d4
