### ISSUE TITLE
lost spaces and formatting in hyperlink

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#23]
Please note that, in a fragment similar to the following,
the spaces after "Instrum." and after "88" are lost
and the boldface of "88" is also lost (or applied to the whole hyperlink maybe)

```xml
...<w:t xml:space="preserve">Rev. Sci. Instrum. </w:t></w:r>
<w:r w:rsidR="00A51604" w:rsidRPr="002E01AB"><w:rPr><w:rStyle w:val="af1"/><w:b/><w:bCs/><w:color w:val="auto"/><w:lang w:val="en-US"/></w:rPr>
<w:t xml:space="preserve">88 </w:t>...
```
TeX becomes:
```tex
Rev. Sci. Instrum.88(2017) 033504
```
MWE here:
https://medialab.sissa.it/owncloud/index.php/s/qPdO4qMBWdU28RH

**Comment by mkraetke** [comment]
Our typesetters wanted that markup such as boldface should be wrapped around the hyperlink. But now I removed this behaviour with commit 5ee4c96a29988c0e3b6f8a1b1a256c2cd3e49d0f. Now there are multiple styles allowed in a hyperlink and the whitespace is preserved. I'll discuss this matter with my colleagues. Perhaps we might decide to use internally another solution, but I think for the public configuration this is fine.
