### ISSUE TITLE
lost image and caption (probably related to east-asia chars)

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#25]
Please note that in the translation of the file given below, figure 4 and its caption become (line 89 in the tex file):
```tex
\等线{46 69 ...
```
There is something similar at line 330.

I tried to isolate the problematic part only, but I get a different output (below), so I'm providing the whole document, but please do not distribute it
```tex
\DengXian{46 69 ...
```

Problematic file and translation:
https://medialab.sissa.it/owncloud/index.php/s/4APWPgtO5slLkuA

[OT] I'm opening many issues, please feel free to stop me if I'm too pesky :-)

**Comment by mkraetke** [comment]
It's fine, just create an issue for each problem and thanks for your feedback!

**Comment by gamboz** [comment]
something similar in the following files, where the abstract is lost (l.51)
https://medialab.sissa.it/owncloud/index.php/s/EiFiFn0TETeZxA7

**Comment by mkraetke** [comment]
Hi @gamboz, your assumption was right. There was a zh_CN font applied to the paragraph. Now there is checked in the first place if the paragraph contains other elements.

**Comment by gamboz** [comment]
Thank you, I can confirm that 
https://medialab.sissa.it/owncloud/index.php/s/4APWPgtO5slLkuA
is now correct.

However, in the file
https://medialab.sissa.it/owncloud/index.php/s/EiFiFn0TETeZxA7
I still see (l.45):
\textsc{Abstract:} \TimesNewRoman{41...

**Comment by mkraetke** [comment]
Thanks for your report, I'll have a look into your file.

**Comment by gamboz** [comment]
In the hope it may be useful, please note that, in a similar document, in Word, I did a search-and-replace for font "Times-Roman" and replaced it with "Times New Roman" and the problem disappeared.

**Comment by mkraetke** [comment]
OK, I've added the charset code of this font to our docx2hub module. Now the content is converted properly.
