### ISSUE TITLE
lost space after comment

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#28]
Please note that spaces after comments are lost.
Comment created with "Review" -> "New Comment" (Word 2010).
MWE: https://medialab.sissa.it/owncloud/index.php/s/bjGGPuQemdt6maH

**Comment by mkraetke** [comment]
The whitespace is in the next line, but TeX doesn't render whitespace at the beginning of a new line. Therefore, it is checked for whitespace after the word annotation and inserted before the latex comment.
