### ISSUE TITLE
hidden text not "tagged"

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#29]
Desiderata

Text that has font effect "hidden" is translated as normal text, even if it does not display in a pdf generated from the docx and it does not display in the document when the "formatting symbol" button (¶) is not active.

In the following example, the word "bbb" is "hidden".
Would it be possible to have it translated into something like `\@gobble{bbb}`?

https://medialab.sissa.it/owncloud/index.php/s/VFtUaKfo3chdV82

**Comment by mkraetke** [comment]
Thank you for the sample. It's no problem to enclose the bbb with `\@gobble`. However it seems that the bbb didn't appear. Instead you can now read `Aaa gobblebbb ccc ddd`. Here is my (shortened) output:

```latex
% ...
\usepackage{gobble}
\begin{document}
Aaa \@gobble{bbb} \textbf{ccc} ddd

\end{document}
```

Would be good to know what I did wrong?

**Comment by gamboz** [comment]
My error: the `\@gobble` macro works only in class definitions or wrapped in `\makeatletter` /  `\makeatother`. A possible solution would be to define `\newcommand{\gobble}[1]{}`. For instance (no need for the "gobble" package):

    \newcommand{\gobble}[1]{}
    \begin{document}
    Aaa \gobble{bbb} \textbf{ccc} ddd

For completeness, I've just noticed that there is an extra space left between "Aaa" and "ccc". If possible, the space after "bbb" should also be included in the `\gobble` macro. For instance:


    \newcommand{\gobble}[1]{}
    \begin{document}
    Aaa \gobble{bbb }\textbf{ccc} ddd

However I do not think this is indispensable.

Sorry for my mistake.

**Comment by gamboz** [comment]
Just thinking, maybe a macro named `\texthidden` would reflect better what is happening:

    \newcommand{\texthidden}[1]{}
    \begin{document}
    Aaa \texthidden{bbb} \textbf{ccc} ddd

**Comment by gamboz** [comment]
Any news on this?

> ```
> \newcommand{\texthidden}[1]{}
> \begin{document}
> Aaa \texthidden{bbb} \textbf{ccc} ddd
> ```

thanks :)

**Comment by mkraetke** [comment]
I've decided to put `bbb` just in a comment. Output looks like:
```
Aaa
%bbb
 \textbf{ccc} ddd
```
It's standard tex and we do not need to create a new magic instruction where the compiler will fail.
