### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#30]
I get the following error when I try to translate this file:

    INFO : file:..docx2tex/xpl/docx2tex.xpl:188:38:No custom-font-maps loaded.
    ERROR: file:...docx2tex/xproc-util/load/xpl/load.xpl:0:load-error:Could not load file:...docx2tex/conf/conf.csv (file:...docx2tex/xproc-util/load/xpl/load.xpl) dtd-validate=false
    ...

https://medialab.sissa.it/owncloud/index.php/s/BZFHlref5mB3uAS

(I think my installation is ok, because I can translate other documents)

**Comment by mkraetke** [comment]
Sorry, only docx files are supported. I've added a simple check in the bash script for the file extension. You should open the doc file and save it as docx and then run docx2tex again.
