### ISSUE TITLE
lost most newlines and formatting

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#31]
In the two documents from the link below, the translation looses most (all?) newlines:
https://medialab.sissa.it/owncloud/index.php/s/dCH1jidpubcSFQM

I tried a simple edit, save and translate again without success.

**Comment by gamboz** [comment]
In the hope it may be useful, I've added a Minimal Working Example based on one of the files in the folder above (JINST_064P_1017-v2-MWE.docx).
The problem seems to be related to the Paint Picture embedded in the docx

**Comment by mkraetke** [comment]
Thank you for your report. Meanwhile, I got this output from docx2tex:

```latex
aaa

\includegraphics[width=0.5\textwidth]{JINST_064P_1017-v2-MWE.docx.tmp/word/media/image1.png}\
\includegraphics[width=0.5\textwidth]{embeddings/oleObject1.bin}

bbb
```

The newlines after "aaa" and before "bbb" are preserved. What is your expected output?

**Comment by gamboz** [comment]
Now the output is correct: all files I sent and a couple of other that I had with the same error are now transformed perfectly. I suppose one of the previous commits corrected this.
I think the issue can be closed.
