### ISSUE TITLE
Issues with d2t.bat

### ISSUE THREAD

**Issue by JohnAdders** [transpect/docx2tex#32]
The current version of the d2t.bat file doesn't work correctly it has 2 issues:

- The path to calabash is incorrect
- Exiting the script also exits the shell

The attached patch fixes both these issues
[windows_fixes.diff.txt](https://github.com/transpect/docx2tex/files/1700097/windows_fixes.diff.txt)

**Comment by mkraetke** [comment]
Thank you for your report, I've applied your fix with commit a40bf577c99e66e629fa5e149bd4dceacf0553d8
