### ISSUE TITLE
MathType Support

### ISSUE THREAD

**Issue by Neurrone** [transpect/docx2tex#33]
Any chance of adding MathType support?

**Comment by gimsieke** [comment]
There is MathType support. Do you have an example where it does not work? 
I just noticed that the latest release is older than a year. MathType support has been added 5 months ago. 
Please clone the repo recursively or wait for @mkraetke to create a new release.

**Comment by Neurrone** [comment]
I get the following error after cloning recursively:

```sh
> d2t.bat "D:\tut\test\Tutorial4OML.docx"
'calabash-frontend' is not recognized as an internal or external command,
operable program or batch file.
```

The shell also disappears on any errors - the second line was from the output log. It also breaks with directory paths containing spaces.

Also, what is the difference between using this and configuring transpect? Transpect's setup looks more involved.

**Comment by gimsieke** [comment]
Apparently the patch suggested in #32 hasn't been applied yet. This will fix the calabash path. A fix for spices in file names is only in the Bash scrip, d2t. Perhaps you cane come up with a fix for d2t.bat yourself, since apparently the .bat frontend receives less attention from our part.
Regarding your other question: docx2tex is a configurable converter that is built on libraries of the transpect framework. There is no standalone transpect application.

**Comment by Neurrone** [comment]
I've tested this on 2 versions of the same file:

* The first with equations in Word's equation editor (OML) format
* One with the OML equations converted to MathType OLE objects

Both appear to work flawlessly, this is really an amazing program - the LaTeX is much better than the stuff MathType produces.

Applying #32 fixes all issues except filename with spaces. I'll see if I can submit a PR that applies the earlier patch, and a fix for the space problem.

The only oddities I've noticed are:

* The start of every bulleted item has `\label{mark-1.}`, `mark-2` etc next to the first line of the paragraph. Is there any way of removing that?
* The file I tried is my statistics tutorial, which when opened in Word only shows 3 questions. However, in the LaTeX, I see the output for an additional 4th question not present in Word. Is docx2tex somehow converting deleted content?

**Comment by mkraetke** [comment]
Hey @Neurrone, thanks for your report. I've fixed the issue with the d2t.bat. Feel free to provide us with a PR or a sample file for testing for the other issues, you've mentioned. A new docx2tex release is underway, but there are some issues with our main docx2hub module, which we have to fix first.

**Comment by gimsieke** [comment]
As to deleted content: The docx2hub converter should accept all changes [by default](https://github.com/transpect/docx2hub/blob/c5a877872638e4b5da5ef573931c7f14a2f70579/xpl/docx2hub.xpl#L181). The track changes markup is difficult to process though and there may be bugs. If you want, we can look into this issue. You can send your file via email to letexml@le-tex.de
