### ISSUE TITLE
Problem about time improvment

### ISSUE THREAD

**Issue by hilohg** [transpect/docx2tex#34]
Hi, i have tons of docx files to transform but this project is very time-consuming. I found it generates some temporary files in the process,  i guess this may be the problem. I am not good at shell, could you please offer a solution for me? many thanks.

**Comment by gimsieke** [comment]
Without any data, we cannot judge whether the processing times that you experience can be considered normal or whether there is a hitherto undiscovered performance bottleneck. Also, it will be interesting to see which revision (git commit) of the repositories you are using.
