### ISSUE TITLE
how to obtain a tex file with utf8 chars?

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#36]
I would like to obtain that in the output tex file certain chars stays in utf8 (à) and are not translated into latex macros (\'a).  Is this possible?

I tried to look in the `<charmap>` of conf.xml, but the chars that I want are not there.
I was looking at fontmaps, but, if I understand correctly, I want the opposite of what they would do.

thanks
[aaa.docx](https://github.com/transpect/docx2tex/files/2554026/aaa.docx)

**Comment by mkraetke** [comment]
You can write a custom configuration file and pass it via the `-c` parameter at the command line. Import the original docx2tex configuration and just override the character mappings.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<set xmlns="http://transpect.io/xml2tex">

  <!-- import the docx2tex configuration file -->
  <import href="conf/conf.xml"/>
  
  <!-- just override a specific character mapping 
       to keep the unicode -->
  
  <charmap>
    <!-- if you want to keep the unicode character, just 
         override the mapping of &#x2022; to \textbullet -->
    <char character="&#x2022;" string="&#x2022;"/>
  </charmap>

</set>
```

**Comment by gamboz** [comment]
thank you, that works
however, I think that I am missing something, since I cannot find

**Comment by mkraetke** [comment]
You're right, there is an additional function which takes care of unicode combining characters. I've developed this function to avoid explicit mapping of all combinations of combining characters. But I have to admit that we need a specific UTF-8 output option here. I'll put this in the next release. We can leave this issue open until this option is included.

**Comment by gamboz** [comment]
that would be very good indeed
thank you :+1:

**Comment by mkraetke** [comment]
I did recently some work on improving the configuration. To deactivate the automatic conversion of diacritical characters to its TeX equivalents e.g. `&#x6f;&#x308; → \"{o}`, you can add `decompose-diacritics="no"` to `<set>`. If you want to ignore certain character mappings from imported configurations, you can add `ignore-imported-charmaps="false"` to `<charmap>`. Here is a minimal configuration to completely deactivate the character mapping from docx2tex. 

```xml
<set xmlns="http://transpect.io/xml2tex" decompose-diacritics="yes">
  
  <import href="docx2tex/conf/conf.xml"/>
  
  <charmap ignore-imported-charmaps="false"/>
  
</set>
```

This issue reminds me that I should restrict boolean values either to `yes|no` or `true|false` or accept both. 😅
