### ISSUE TITLE
Citavi→BibTeX

### ISSUE THREAD

**Issue by gimsieke** [transpect/docx2tex#39]
Citavi 6 seems to store its references as base64-encoded JSON in field codes. There has been a request to transform them into BibTeX. 
We will do this if we receive at least € 960 of external funding for it. The user who requested the feature is currently considering sponsorship (that is, committing to the full amount).

**Comment by mkraetke** [comment]
I guess we can safely close this issue since you implemented the Citavi JSON and me the Citavi XML format. Since then there were no complaints or nobody is using this feature.
