### ISSUE TITLE
regression (?) between 1ebf3cf and 74c5b4d

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#40]
I think that the file [JINST_001P_1018.docx](https://github.com/transpect/docx2tex/files/2690488/JINST_001P_1018.docx) translates correctly in
1ebf3cf (Oct 17 change mapping of x131)
but fails in 
74c5b4d (Nov 7 update mml2tex)
and following versions (but I think with different errors).

**Comment by mkraetke** [comment]
We separated the [fontmaps](https://github.com/transpect/fontmaps) from docx2hub. Now they are re-added as submodule and it should work fine.

**Comment by gamboz** [comment]
confirmed
thank you
