### ISSUE TITLE
possible regression in commit e219cf8

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#42]
Hi, it is possible that some error crept in with commit e219cf8
I have a working d2t until commit 53d293b, but with the next one I get some errors.
Example:

git checkout --recurse-submodules 53d293b
d2t Untitled.docx 
docx2tex finished.

git checkout --recurse-submodules e219cf8
d2t Untitled.docx 
Errors encountered while running docx2tex. Please see Untitled.d2t.log for details.

[Untitled.d2t.log](https://github.com/transpect/docx2tex/files/2982516/Untitled.d2t.log)

[Untitled.docx](https://github.com/transpect/docx2tex/files/2982500/Untitled.docx)

**Comment by mkraetke** [comment]
Some submodules were out of date and didn't align with docx2tex anymore. I fixed this a few minutes ago.

**Comment by gimsieke** [comment]
@mkraetke A new release might be appreciated by the non-Git-client users…

**Comment by mkraetke** [comment]
@gimsieke agree, but first:

![russian-doll](https://user-images.githubusercontent.com/983392/54596992-068b6980-4a36-11e9-96da-faf095cbe2e5.jpg)
