### ISSUE TITLE
question re conf.xml

### ISSUE THREAD

**Issue by therealpaperclip** [transpect/docx2tex#48]
How would I configure the conf.xml to produce an **article** instead of a **book**? Is there a basic *conf.xml* for **articles**?

**Comment by mkraetke** [comment]
Hey, seems that we didn't take notice of your question. We're deeply sorry about this! You can create your own configuration file, store it for example to `conf/myconf.xml ` and import the default docx2tex configuration. Here is a brief example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<set xmlns="http://transpect.io/xml2tex">
  
  <import href="conf.xml"/>
  
  <preamble>
    \documentclass{article}
    % your custom package declarations go here
  </preamble>

</set>
```

Then you can invoke your configuration file with `./d2t -c conf/myconf.xml myfile.docx`. For more information on how to customize your configuration, please refer to the [xml2tex README](https://github.com/transpect/xml2tex/blob/master/README.md). Please take aslo notice, that the configuration is applied on an intermediate XML format, which is stored under the same basename of your DOCX input file, e.g. `myfile.xml`.
