### ISSUE TITLE
Is this the project relatex to docx2latex.com?

### ISSUE THREAD

**Issue by kopax** [transpect/docx2tex#49]
Hi, I am looking for the source code that generated from google doc latex document.

I wonder if this is the script used by docx2latex.com, with this script I am not getting the same result and perhaps I am missing something.

Thanks in advance,

**Comment by gimsieke** [comment]
We (that is, @le-tex, the company behind the open-source transpect conversion framework) are not affiliated with https://docx2latex.com/ and we don’t know which software they are using internally or how the conversion results of the two tools differ.

**Comment by gimsieke** [comment]
Regarding conversion from Google docs to LaTeX: We use the docx export from Google docs, we don’t convert their document representation natively. Last time I checked, equations entered in Google docs were only included as images in the docx export, so these won’t be converted to proper LaTeX formulas when converting gdoc’s docx export.

**Comment by mkraetke** [comment]
Just checked out [docx2latex.com](https://docx2latex.com) and they use their own software. In contrast to our project, they lack of a proper MathType conversion and just include the preview images:
```tex
\begin{figure}[H]	\begin{subfigure}		\includegraphics[width=0.45\textwidth]{./media/image1.pdf}
	\end{subfigure}
~	\begin{subfigure}		\includegraphics[width=0.45\textwidth]{./media/image1.pdf}
	\end{subfigure}
~
\end{figure}
```
Feel free to find more about the differences between the two projects.

**Comment by kopax** [comment]
Very clear, thanks a lot for replying that fast! And thanks for doing it open source, that's what the world needs.
