### ISSUE TITLE
Problems with symbols and accented characters

### ISSUE THREAD

**Issue by j3mdamas** [transpect/docx2tex#5]
The reference file is the same as #3.

I am not sure of how `doc2tex` should be dealing with these issues, but while symbols like the alpha or beta characters are converted to `$\alpha$` or `$\beta$`, other symbols are not being recognized. Some examples include the minus or times signs, apostrophe (for example, see «Kramers'» in the file), or tildes (which should be converted to `\~{}` or `\textasciitilde{}`).

Moreover, some accented characters, like in my name, are not being recognized, but comparing with the output from codeplex's `doc2tex`, I identified this problem to be the lack of `\usepackage[utf8]{inputenc}` in the preamble. Am I correct?

About the lone symbols, is there anything that can be done?
Also, can `doc2tex` recognize the differences between types of dashes (see [here](https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Dashes_and_hyphens))?

Cheers

**Comment by gimsieke** [comment]
Honestly I don’t know why the colleagues didn’t opt for UTF-8 encoding in first place.
Maybe you can fix some urgent stuff in your version of of [texmap.xml](https://github.com/transpect/mml2tex/blob/master/texmap/texmap.xml)? If you do, you can certainly issue a pull request afterwards.

**Comment by j3mdamas** [comment]
Thanks for the tip on the `texmap.xml` file. I will try to into it soon and report back.
About the accented characters, the best is then to add the package or to convert the characters to `\<accent>{<character>}` in the `texmap.xml`, for example? (I am not sure the latter is even possible)

**Comment by gimsieke** [comment]
It should be absolutely feasible to add them to the map. But I’m currently not sure whether this map only applies to math content since it’s in mml2tex. Maybe @mkraetke likes to tune in and give us some insights? (nudge nudge)

**Comment by mkraetke** [comment]
I'll decompose the diacritical characters and then write a proper replacement in xml2tex.xsl

**Comment by mkraetke** [comment]
Diacritical marks are now converted by the function xml2tex:convert-diacrits. Unfortunately there is not for every diacritical mark a proper equivalent in LaTeX text mode. But if you miss something @j3mdamas, please let me know.
