### ISSUE TITLE
funny translations: \TimesNewRoman{56 41 43...

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#50]
The translation of the attached file results in a lot of macros in the following form:
\TimesNewRoman{41 43...

As soon as I open the docx in word and save it, the problem disappears.

Might be related to issues/25

(please do not distribute the attached file)
[wj.docx](https://github.com/transpect/docx2tex/files/3742764/wj.docx)

**Comment by gamboz** [comment]
another example
(same workaround as before: open the docx file, add a space, save and translate again)
[example2.docx](https://github.com/transpect/docx2tex/files/4102912/example2.docx)

**Comment by mkraetke** [comment]
Reason was an odd font charset code in docx. Added the code and now it works for both files.

**Comment by gamboz** [comment]
thank you
do you know if the next release of docx2tex has already been scheduled?

**Comment by mkraetke** [comment]
I'm planning a new release for the midst of february.

**Comment by rishinair** [comment]
I am getting \TimesNewRoman{41 62 73 74 72 61 63 74} and similar coding in few files. I'm sorry that I will not be able to share the documents to due to copyright issues. So would just the font table (files.docx.tmp/word/fontTable.xml) be enough?

**Comment by mkraetke** [comment]
Please provide a minified docx file. I'm afraid the font table alone might not be enough.

**Comment by rishinair** [comment]
Thank you :)

Once I resave the file or copy and paste the content to a different file, I can convert without any problem. So I am sorry that I am not able to provide a sample file to you for testing. If any other file which is part of the docx zip file would be enought, please let me know. Or if there is any other location in any files which I can look into to find the font name or any string, please let me know.
