### ISSUE TITLE
FATAL: Failed to parse Saxon configuration file.

### ISSUE THREAD

**Issue by FrankLiu007** [transpect/docx2tex#51]
I want to use docx2tex to test whether it can convert mathtype equation to latex. 
I use the most recent docx2tex release. 
I got error message as below:

FATAL: Failed to parse Saxon configuration file.
java.nio.file.InvalidPathException: Illegal char <*> at index 67: C:\docx2tex\calabash\extensions\transpect\javascript-extension\lib\*

This is my docx file.
[equation.docx](https://github.com/transpect/docx2tex/files/3901591/equation.docx)

**Comment by gimsieke** [comment]
Which Java version are you using?

**Comment by FrankLiu007** [comment]
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
，windows10

**Comment by FrankLiu007** [comment]
Yes, java1.8 works well
