### ISSUE TITLE
Errors encountered while running docx2tex

### ISSUE THREAD

**Issue by i94loveu** [transpect/docx2tex#56]
system win 10
java version "1.8.0_251"
docx2tex-1.4-release.zip
log:
错误: 找不到或无法加载主类 com.xmlcalabash.drivers.Main
原因: java.lang.ClassNotFoundException: com.xmlcalabash.drivers.Main
错误: 找不到或无法加载主类 com.xmlcalabash.drivers.Main
错误: 找不到或无法加载主类 com.xmlcalabash.drivers.Main

**Comment by gimsieke** [comment]
Might be [this issue](https://github.com/transpect/mathtype-extension/issues/15#issuecomment-615072812)

**Comment by mkraetke** [comment]
@i94loveu I've updated the docx2tex 1.4 release and corrected the classpath in the batch file. Please download the release and try again.

**Comment by i94loveu** [comment]
> @i94loveu I've updated the docx2tex 1.4 release and corrected the classpath in the batch file. Please download the release and try again.

new Errors
'calabash' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by mkraetke** [comment]
Thanks for your report, I fixed the other classpath and updated the release.
