### ISSUE TITLE
regression in 1.4

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#57]
I'm attaching a docx that translates well with docx2tex 1.3 but not with release 1.4.
The translation ends with error
```bash
ERROR: file://...docx2tex/xproc-util/xslt-mode/xpl/xslt-mode.xpl:0:xslt-mode-apply-xpath:A sequence of more than one item is not allowed as the result of a call to xml2tex:langs-to-latex-pkg#1
```
(please do not distribute the file :)
[JINST_003T_1219.docx](https://github.com/transpect/docx2tex/files/4492296/JINST_003T_1219.docx)

**Comment by mkraetke** [comment]
Thanks for reporting this issue, I'll have a look into it

**Comment by mkraetke** [comment]
Issue was caused by a wrong result type of a new function. Changes are included in the master branch.

**Comment by gamboz** [comment]
Thank you, I confirm good translation with a clone of the master for the previous file.

However, I think I have another issue. Here is the file that fails this time: 
[JINST_152P_0120.docx](https://github.com/transpect/docx2tex/files/4492526/JINST_152P_0120.docx)

(please let me know if you prefer that I open a new issue)

**Comment by mkraetke** [comment]
An XSLT mode crashed because of an inconsistent map declaration in our DrawingML2SVG converter. This issue is now fixed, too.

**Comment by gamboz** [comment]
thanks, all fine now
