### ISSUE TITLE
error processing file

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#58]
Hi, I have some errors processing the attached file.
I'm using release 1.5; the first error I see is
```
ERROR: docx2tex/xproc-util/load/xpl/load.xpl:0:load-error:Could not load file:/tmp/docx2tex/conf/conf.csv (file:///tmp/docx2tex/xproc-util/load/xpl/load.xpl) dtd-validate=false
```

[JINST_007T_1219.docx](https://github.com/transpect/docx2tex/files/4523482/JINST_007T_1219.docx)

**Comment by mkraetke** [comment]
The mentioned error can safely be ignored. docx2tex just looks for a alternative CSV configuration file and if the file cannot be loaded, it loads the XML configuration. However the crash is again caused by the DrawingML-2-SVG module. I'll have a look into.

**Comment by mkraetke** [comment]
The issue was related to a missing line pitch value. I added a fallback value when the line pitch is not given in the DOCX. The file converts now properly and the changes are in the master branch.
