### ISSUE TITLE
error processing file

### ISSUE THREAD

**Issue by gamboz** [transpect/docx2tex#59]
I have errors processing the this file: 
[JINST_005P_0420.docx](https://github.com/transpect/docx2tex/files/4545455/JINST_005P_0420.docx)

Might be related to #58 (not sure)

**Comment by mkraetke** [comment]
Thanks for your report, I'll have a look into it.

**Comment by mkraetke** [comment]
The error was caused by missing relative positioning values for inline Drawing ML graphics and I inserted reasonable default values to circumvent this issue. If there are any other issues, don't hesitate to report them. Your feedback is always welcome!
