### ISSUE TITLE
Formatting issues with in-text (sub|super)scripts

### ISSUE THREAD

**Issue by j3mdamas** [transpect/docx2tex#6]
The reference file is the same as #3.

I am experiencing some issues with subscripts and superscripts in the reference file.

1) I think there in a lack of brackets for longer subscripted words, with *k*<sub>cat</sub> being converted to `\textit{k}$_cat$/` instead of `\textit{k}$_{cat}$/`.
2) Issues with the superscript when the following character in a minus sign, like `$^−1$` (maybe related with issue #5?)
3) I am getting double-equation mark-up for C<sup>α</sup>, like this `C$^$\alpha$$`. This screws things and a lot of the non-equation text following it is pulled into the equation mode.

Cheers

**Comment by mkraetke** [comment]
1) issue with brackets in sub/superscripts is resolved.
2) should be fixed with 1)
3) this problem occurs when superscript/subscript (`C$^{α}$`) contains text characters which are replaced with math mode characters in the configuration file. (`C$^{$\alpha$}$`).
