### ISSUE TITLE
'Java is not recognized error

### ISSUE THREAD

**Issue by csullivan107** [transpect/docx2tex#65]
'java' is not recognized as an internal or external command,
operable program or batch file.

This was the only thing in the log file after an error occured. Any thoughts? I am not familiar with anything java

**Comment by gimsieke** [comment]
http://letmegooglethat.com/?q=install+java

**Comment by gimsieke** [comment]
Sorry we cannot answer questions at this basic level. If you don’t know what Java is and how to remedy its absence on your computer, you will almost certainly run into other basic issues that we are unable to answer in order not to get distracted from our core responsibilities. This is an open-source software that comes as it is. Either find out how to run it yourself or leave it.
