### ISSUE TITLE
Undefined color '{color-1}

### ISSUE THREAD

**Issue by pryme-svg** [transpect/docx2tex#68]
![image](https://user-images.githubusercontent.com/65417452/101193285-3404b600-3611-11eb-8cfc-656ec7dd8576.png)

I get this error after compiling.

**Comment by mkraetke** [comment]
It seems that a color is used, which is not in the list of defined colors. Can you please provide me your DOCX file then I can analyze and hopefully fix your issue?

**Comment by pryme-svg** [comment]
Here is the docx file (with only the problematic part)
[test.docx](https://github.com/transpect/docx2tex/files/5644407/test.docx)

console logs: https://pastebin.com/afRmXA28

**Comment by mkraetke** [comment]
Thanks for providing the file. I'll have a look under the hood.

**Comment by pryme-svg** [comment]
Seems like its just the highlighting that screws it up

**Comment by mkraetke** [comment]
The issue wasn't a unspecified color but that `\colorbox` was wrapped inside of other styles, so I changed the rule priority for `\colorbox` that it is processed before other text styles.

```latex
(\colorbox{color-1}{\ul{\textbf{\textit{test}}}})
```

You just need to update the master branch.

**Comment by pryme-svg** [comment]
cool thanks!

**Comment by mkraetke** [comment]
Thanks for your report!
