### ISSUE TITLE
Equation-related issues (\underset, \sum\nolimits, \substack, cases environment)

### ISSUE THREAD

**Issue by j3mdamas** [transpect/docx2tex#7]
The reference file is the same as #3.

1) I use some sum-class symbols in-text and the limits are always on the right of the sigma symbol. But `doc2tex` is recognizing this and using the `\underset{<limits>}{\sum}` instead of the more common `\sum\nolimits`. In fact, this is also happening in the equations not in-text, but I am guessing that's because they are inside the tabular environment.
2) Limits of sums with more than one line (see equation 2 of reference file) are being transformed into an array environment. I think the best solution would be to use [`\substack`](https://tex.stackexchange.com/a/80461) (maybe [`\mathclamp`](https://tex.stackexchange.com/a/33358) could also help here)

Cheers

**Comment by j3mdamas** [comment]
Oh, and
3) Is there the possibility of using the [`cases` environment](https://en.wikibooks.org/wiki/LaTeX/Advanced_Mathematics#The_cases_environment) for equations 4 and 5?

**Comment by gimsieke** [comment]
I already implemented cases in https://github.com/transpect/mml2tex/commit/074db86b6287622154322d422cbba56a6cc4b965

**Comment by j3mdamas** [comment]
OK, I didn't notice that. You are right, there is the cases, it is just that the `&` to separate the conditions (second clause on each sentence) from the function is not being used, but I guess it is impossible for `doc2tex` to know/interpret that. I will do that by hand. Point 3) is solved.

**Comment by gimsieke** [comment]
The & isn’t used because you used spaces for indentation. You need to create a matrix inside the curly brace in order to get proper alignment.

**Comment by j3mdamas** [comment]
yeah, lesson learned for the next time I write such equations on MS Word ;)
