### ISSUE TITLE
{quotation} environment and alignment - Issues

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#71]
1. A quote possibly set as a quote in a word document, has been converted as a regular text in bold font which should have been converted within {quotation} environment.
2. In another instance author has set some different text in left, center and right alignment. However the equivalent LaTeX code for these alignment were not converted into the TeX file.
3. Is there any chance the captions of tables and figures be included within the {table} or {figure} environment within \caption{}?

I can provide you with the docx file with which I am trying if you can provide an email id.

I would also like to say I have the above issues in version 1.5. The conversion with multi-lined display equations and tables are very much improved now. Thank you so much for the enhancements.

**Comment by mkraetke** [comment]
A question to (1) by "set as quote" you mean you used the paragraph style named "quote"? Can you provide me a docx file which contains the mentioned issues? Without to look at the code, it's hard to solve your issues.

**Comment by rishinair** [comment]
Thanks for the quick response. I have sent a sample docx file to your personal email.

**Comment by rishinair** [comment]
Another problem noticed is that, the opening and closing double quotes in previous versions appeared rightly as `` ... '' (ie, for opening two left single quotes and for right two right single quotes). However, in this version both the opening and closing are the same double quote ". Can this one also be checked and corrected?

**Comment by mkraetke** [comment]
I checked the issues and will have a look into the wrong quotes. I will get back to you soon.

**Comment by rishinair** [comment]
In a paragraph which starts with "Basic rule of references ...", you can see the following code is converted in the TeX code, but when I check the word document, it was actually not done as quote, but can see only a highlighted text. Could you please look into this also?

\begin{quote}
(3)
\end{quote}

**Comment by mkraetke** [comment]
1. Fixed this issue, the MS Word paragraph styles for quotes are now recognized.
2. Paragraphs are now aligned with `\begin{center} … \end{center} ` and `\begin{flushright} … \end{flushright`.
3. Table and figure captions are not included but under the condition that they have the MS Word paragraph style `Caption` or `Beschriftung` (german) and are above the table or below the figure. This reflects how MS Word usually place captions. There is no detection via regular expressions such as "paragraph starts with 'Table 1'".
4. I removed the mappings for quotation marks earlier, since you can just include this line in your tex preamble to make them work: `\usepackage[utf8]{inputenc}`
5. fixed this together with 1.

**Comment by rishinair** [comment]
Thank you so much for fixing these issue so quickly. Much appreciated. 

When can we expect the latest release with the above changes incorporated?

Regarding the item 4, I actually want the TeX file to convert to XML and not to a PDF document. Hence for us it was a great help when the quotes are marked as `` ... ''.

**Comment by mkraetke** [comment]
Just released docx2tex and changed the quotes accordingly. Hope nobody complains about the changed quotes ;)

**Comment by rishinair** [comment]
Thank you so much Martin, really helpful! 

Will check and give feedback as early as possible.

**Comment by rishinair** [comment]
I have checked the latest version and I am happy to report that everything worked like a charm and the reported issues are not seen any more. Thank you so much. 

This tool is very much helpful and I am testing with more docx files. I will report any issues which I come across during the testing.

**Comment by mkraetke** [comment]
Thank you for your kind post. Bug reports from users are also very welcome and help to improve docx2tex.
