### ISSUE TITLE
Email, URL, ORCID etc

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#72]
&lt;link xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="mailto:someone@email.com">
      &lt;phrase role="Hypertextovodkaz" css:font-size="12pt">someone@email.com</phrase>
    &lt;/link>

   &lt;link xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://orcid.org/0000-1111-1111-1111">
      &lt;phrase role="Hypertextovodkaz">https://orcid.org/0000-1111-1111-1111</phrase>
    &lt;/link>

   &lt;link xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://www.sciencedirect.com/topics/engineering/test-link">
      &lt;phrase css:color="#000000">Test link</phrase>
    &lt;/link>

I got the above codes in the file.xml, when I converted a docx file. I believe from the file.xml, the file.tex will be created. Is there any possibility, I can convert them into the respective TeX coding which I want. For example:

1. \email{someone@email.com}
2. \orcid{https://orcid.org/0000-1111-1111-1111}
3. \href{https://www.sciencedirect.com/topics/engineering/test-link}{Test link}

I haved modified the following definition of link as below in conf/conf.xml, but it is not working. ie, I am getting only the printable string like someone@email.com, https:// ... etc.

   &lt;template context="dbk:link[@xlink:href][matches(@xlink:href, '^mailto:')]">
    &lt;!--rule-->
      &lt;text>\email{&lt;/text>&lt;xsl:value-of select="dbk:phrase"/>&lt;text>}&lt;/text>
    &lt;!--/rule-->
  &lt;/template>

**Comment by mkraetke** [comment]
You can create a xml2tex configuration file and pass it to docx2tex with the command line parameter `-c`. Here is a brief example:

```xml
<?xml-model href="http://transpect.io/xml2tex/schema/xml2tex.rng" type="application/xml"
            schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://transpect.io/xml2tex/schema/xml2tex.rng" type="application/xml"
            schematypens="http://purl.oclc.org/dsdl/schematron"?>
<set xmlns="http://transpect.io/xml2tex">

  <!-- import the docx2tex main configuration -->
  <import href="conf/conf.xml"/>
  
  <!-- match links that start with 'mailto:' -->
  <template context="dbk:link[matches(@xlink:href, '^mailto:')]">
    <rule name="email" type="cmd">
      <param/>
    </rule>
  </template>

  <!-- match links that start with 'https://orcid.org' -->  
  <template context="dbk:link[matches(@xlink:href, '^https://orcid.org')]">
    <rule name="orcid" type="cmd">
      <param/>
    </rule>
  </template>
  
</set>
```

docx2tex applies the xml2tex configuration on the intermediate xml output. You can learn more about writing xml2tex configuration files [here](https://github.com/transpect/xml2tex/blob/master/README.md). An necessary prerequisite is to know XML, XSLT and XPath.

**Comment by rishinair** [comment]
Thank you so much Martin.

**Comment by mkraetke** [comment]
As an addition: you can open the oXygen project file `docx2tex.xpr` with the oXygen XML editor. When you edit the file above, oXygen will provide tooltips and autocomplete.
