### ISSUE TITLE
Accents not converted to TeX commands

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#73]
Accents (for example, ý, ě, Š) in names did not get converted to their equivalent TeX commands.

I am using "./d2t -t -l  file.docx"

**Comment by mkraetke** [comment]
Thanks for the report, I'll check this.

**Comment by mkraetke** [comment]
Looks fine to me. Would you provide me an example please?

```tex
\'{y}, \v{e}, \v{S}
```

**Comment by rishinair** [comment]
Sorry, it seems it is correct when I tried in another folder. Please ignore this and you may close this.

Sorry for the inconveniences.
