### ISSUE TITLE
Appearing "\backslash \_" instead of "\_" in math

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#75]
The following text in a docx file 
 
  where Ccc_i is the cost

now converted as:

where \textit{C}$_{\mathrm{cc\backslash \_ }}$$_{i}$ is the cost

The actual/correct should be 

where \textit{C}$_{\mathrm{cc\_ }}$$_{i}$ is the cost
[document3.docx](https://github.com/transpect/docx2tex/files/5956486/document3.docx)

Please find attached document3.docx.

**Comment by rishinair** [comment]
Apostrophe isn't now a keyboard character? Its in utf-8 format. Would it be possible to change to keyboard character again as it was before?

**Comment by mkraetke** [comment]
Thanks for your report! The fix mentioned above should slove your issue.
