### ISSUE TITLE
Fontstyle/shape coding comes unnecessarily

### ISSUE THREAD

**Issue by rishinair** [transpect/docx2tex#77]
Please find attached font-style-example.zip which contains fontstyle-example.docx and fontstyle-example.tex. 

\textup{} and \textnormal{} commands appear unnecessarily in many files. 
[font-style-example.zip](https://github.com/transpect/docx2tex/files/5963779/font-style-example.zip)

**Comment by mkraetke** [comment]
Thanks, I'll have a look into

**Comment by mkraetke** [comment]
With this commit 4900adf1c08a6d2f3ecc10d9a7d45b6f0f692143, docx2tex applies only `\textnormal` or `\textup` if this is required due to inherited styles.
