### ISSUE TITLE
Conversion Error: Mtef2Xml (NotImplementedError)

### ISSUE THREAD

**Issue by ethanahlquist** [transpect/docx2tex#78]
Howdy, 

I have used docx2tex before without issues. 

However, this time upon attempted convert, I get these errors (and I have few ideas on how to start debugging):

```
.
.
.
WARNING: All illegal access operations will be denied in a future release
NotImplementedError: Only MTEF Version 3 and 5 currently supported, version is 2
  initialize at uri:classloader:/mathtype.rb:19
      <main> at <script>:1
[ERROR] Mtef2Xml: (NotImplementedError) Only MTEF Version 3 and 5 currently supported, version is 2
NotImplementedError: Only MTEF Version 3 and 5 currently supported, version is 2
  initialize at uri:classloader:/mathtype.rb:19
      <main> at <script>:1
[ERROR] Mtef2Xml: (NotImplementedError) Only MTEF Version 3 and 5 currently supported, version is 2
NotImplementedError: Only MTEF Version 3 and 5 currently supported, version is 2
  initialize at uri:classloader:/mathtype.rb:19
      <main> at <script>:1
[ERROR] Mtef2Xml: (NotImplementedError) Only MTEF Version 3 and 5 currently supported, version is 2
Message: Mode: docx2hub:resolve-tblBorders
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
	at java.base/java.lang.StringUTF16.newString(StringUTF16.java:1025)
	at java.base/java.lang.StringBuffer.toString(StringBuffer.java:716)
	at java.base/java.io.StringWriter.toString(StringWriter.java:218)
	at net.sf.saxon.query.QueryResult.serialize(QueryResult.java:60)
	at net.sf.saxon.s9api.XdmNode.toString(XdmNode.java:477)
	at com.xmlcalabash.runtime.XForEach.run(XForEach.java:80)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94)
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262)
	at com.xmlcalabash.runtime.XTry.run(XTry.java:98)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94)
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236)
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136)
	at com.xmlcalabash.drivers.Main.run(Main.java:369)
	at com.xmlcalabash.drivers.Main.run(Main.java:112)
	at com.xmlcalabash.drivers.Main.main(Main.java:83)
```

Any comments would be appreciated. Here is the file I am converting...
[Reference_Manual.docx](https://github.com/transpect/docx2tex/files/5967717/HEC-RAS_6.0_Reference_Manual.docx)

**Comment by gimsieke** [comment]
I don’t think that the unsupported MathType objects are responsible for the crash. It is rather lack of main memory (“`java.lang.OutOfMemoryError`”). The file is pretty large. You should increase the amount of main memory that the JVM is allowed to use. Unfortunately, there is currently no option for that in `d2t` or `d2t.bat`. Which one are you using? We can give you instructions how to patch them in order to increase the maximal memory value. How much RAM does your computer have?

About MTEF (MathType) version 2 support: It is highly unlikely that someone will step in and implement this feature.

**Comment by ethanahlquist** [comment]
Thanks for the feedback, I am running on linux (d2t), but can switch to my windows partition if needed.

RAM:
 ```
myDesktop$ free -h

               total        used        free      shared   buff/cache   available
Mem:            15G        4.6G        2.3G        1.6G         8.6G        9.0G
Swap:          2.0G          0B        2.0G
```

**Comment by gimsieke** [comment]
If you checked out docx2tex from github, you can do a `git pull` now. If you installed it by unpacking the zip, you need to download [d2t](https://raw.githubusercontent.com/transpect/docx2tex/master/d2t) and replace your script with this new version.

There is a new `-h` option. You can use it like this:

```bash
./d2t -h 4096m -d ../tmp/HEC-RAS_6.0_Reference_Manual.docx
```

Let’s hope that 4 Gig suffice… The single-tree XML of the word file comprises 54 MB, the internal representation is about 3× this size, and there are about 20 XSLT passes over the document (with later passes operating on reduced sizes, but still), and unfortunately the intermediate documents may not be discarded, so it might use about 3 GB. And it takes time. Sorry for that. The amount of time that it takes, among other factors, depend on the number of MathType equations.

**Comment by gimsieke** [comment]
(By default the Java process is launched with `-Xmx1024m`.)

**Comment by ethanahlquist** [comment]
Thank you so much! You're actually a lifesaver!

**Comment by gimsieke** [comment]
You’re welcome. 

Did the TeX→PDF rendering run smoothly? My LaTeX on Cygwin (texlive 20200406-2 with some additional packages) choked on a missing soul.sty, on .wmf graphics files, and on missing Spanish support for Babel. Then on a runaway argument in (“Paragraph ended before `\multicolumn` was complete.”). Of which errors I could only fix the missing Spanish support. 
And you might need to proofread closely in order to identify the 3 MTEF v2 equations that must be missing in the tex file. The conversion of the 1066 MathType objects alone took 14 minutes on my laptop, the rest took another approx. 10 minutes.

**Comment by ethanahlquist** [comment]
Yes it did. Most of the equations were generated properly. Yeah, it took around 8 minutes to run, but I'm sure its a little slower running through Cygwin.

There were around 11 comments saying this (in the output.tex):

`% D2T: Empty equation removed!`

and 3 saying:

`% D2T: Equation not converted. See log for details!`

Which is really isn't many failed equations. So I would consider it a success.

**Comment by gimsieke** [comment]
Your computer is simply faster than mine. Cygwin doesn’t slow things down, at least not computations that run in the JVM (which is a Windows JVM btw) and that don’t do much IO. 

I’m glad the output is sufficiently usable. If there are other issues with the conversion, please file new Github issues for them.
