### ISSUE TITLE
*.tmp folder outside the -o folder

### ISSUE THREAD

**Issue by j3mdamas** [transpect/docx2tex#8]
This is a minor issue, but when I run `doc2tex` with the -o option, the *.tmp folder, which contains stuff like the media folder with the images to be inserted, is placed outside the -o folder, so the path for the images is wrong and they are not loaded when the .tex is compiled.

Cheers

**Comment by mkraetke** [comment]
Thank you for your report. Now the file is copied first in the output directory and then converted, so the generated paths are correct.
