### ISSUE TITLE
doc2tex again giving "identical files" error

### ISSUE THREAD

**Issue by gsfs** [transpect/docx2tex#80]
I just downloaded docx2tex-1.6-release.zip to a Mac running Mojave

When I try a conversion, I get this error:
$ ./d2t pset4newproblems.docx pset4temp.tex
starting docx2tex
Errors encountered while running docx2tex. Please see /Users/gsfs/Desktop/pset4newproblems.d2t.log for details.

$ more pset4newproblems.d2t.log 
cp: /Users/gsfs/Desktop/pset4newproblems.docx and pset4newproblems.docx are identical (not copied).

I see this reported and solved in an Issue several years ago but it seems to be back.

**Comment by mkraetke** [comment]
Thanks for your report. Would you please provide me your log file? For privacy concerns, you can send it via email. You can find my email [here](https://www.le-tex.de/de/MartinKraetke.html).

**Comment by gsfs** [comment]
Which log file do you need?  If it's the file created when I ran ./d2t, that is attached.

  Cheers,
  George

=================
George S.F. Stephans
24-408 MIT
(617)-253-4237

**Comment by mkraetke** [comment]
I just need the file pset4newproblems.d2t.log and I'm afraid it seems to me that the file is not attached to this issue.

**Comment by gsfs** [comment]
[pset4newproblems.d2t.log](https://github.com/transpect/docx2tex/files/6092919/pset4newproblems.d2t.log)

**Comment by gsfs** [comment]
My apologies, I sent it by email and forgot to add it to the issue. It's there now.

**Comment by gimsieke** [comment]
Looking at the logfile, I start to think that the `cp`/identical files issue isn’t causing the error. The next line says: 
> No Java runtime present, requesting install.

The XProc processor invocation assumes that there is a `java` program on the search path. If your Java binary is known by a different name, we need to tweak the XProc invocation script a bit so that you can override it. 

If you don’t have a Java runtime installed, you should do so. 

Bash and Java (and LaTeX if you want PDFs to be generated) are about the only prerequisites for running this tool.

**Comment by gsfs** [comment]
That was the problem. I had not had a need for command line java and so didn't have the JDK installed. It all works now. What a nice piece of software!

**Comment by gimsieke** [comment]
Thank you, that’s nice to hear. 

As maintainers of this software, we get to hear that something’s broken much more often than that it’s working Ok, so we appreciate your feedback!

**Comment by gsfs** [comment]
Hi Gerrit.

   I'm not very fluent in Unix and so my apologies if this is an ignorant question. I tried running d2t with an input file in a MacOS directory with blank spaces in the name and it failed. I was in that directory when I ran the d2t. Looking in the massive log file, it seemed to be rendering the directory using %20 instead of \ . I also tried running the d2t from the next higher directory and giving the directory name explicitly:
  $ d2t Spring\ 2021/pset4.docx

That had the same problem. Clearly, I can solve this trivially by renaming my folder to get rid of the blank spaces but I'm curious why this fails.

  Many thanks for all of your help and many, many, many thanks for such a nice piece of software.

  Cheers,
  George

================= 
George S.F. Stephans
24-408 MIT
(617)-253-4237

**Comment by gimsieke** [comment]
> Thank you, that’s nice to hear.
> 
> As maintainers of this software, we get to hear that something’s broken much more often than that it’s working Ok, so we appreciate your feedback!

When I spoke of “maintainers”, I was thinking of all developers of the transpect libraries. But credit where it’s due: The initiator, main developer, and maintainer of docx2tex, which by the way is the single most downloaded transpect application, is @mkraetke. Thank you, Martin!
