### ISSUE TITLE
textcolor in ul

### ISSUE THREAD

**Issue by BravoBaldo** [transpect/docx2tex#83]
After conversion I have to change
   "\ul{\textcolor{color-??}{.}}"
to
   "\ul\textcolor{color-??}{.}"
to avoid errors.
How I can avoid this?
docx2tex ver. 1.6
TeXworks

**Comment by BravoBaldo** [comment]
also
"\ul{\textit{\textcolor{color-8}{blue noise}}}" --> "\ul\textit{\textcolor{color-8}{blue noise}}"
"\ul{\textbf{\textcolor{color-6}{P}}}"			--> "\ul\textbf{\textcolor{color-6}{P}}"

**Comment by mkraetke** [comment]
Thank you for your report, but only from the output, I cannot figure out the cause of your issue. Please provide a small DOCX example and I may help you with a solution.

**Comment by mkraetke** [comment]
Issue was because `\ul` from the soul package has issues with other tex code inside the argument. For underlining, I've changed from soul to ulem package. You just have to pull the master branch.
