### ISSUE TITLE
Produce LaTeX file without \begin{document} and \end{document}

### ISSUE THREAD

**Issue by SamueleSalvia** [transpect/docx2tex#85]
Hi there, thumbs up for this awesome project!

I need to generate a TeX document from a docx file but I'd like the output document not to feature \begin{document} and \end{document} statements. In essence, this output document will have to be embedded in a bigger, regular TeX file. This bigger file is something like:

%preamble
\begin{document}
 %somestuff
\input{my_converted_document}
%someotherstuff
\end{document}

This is the reason why the converted document shouldn't have any preamble nor begin/end document.
I managed to get rid of the preamble in the converted document by commenting out the <preamble> tag in the xml conf file, but I can't figure out how to get rid of the \begin{document} and \end{document} statements.
Can you help me out?

**Comment by mkraetke** [comment]
`\begin{document}` and `\end{document}` are written by [xml2tex/xsl/xml2tex.xsl]. You can just comment [line 59](https://github.com/transpect/xml2tex/blob/82cd2ad06a7bc2b8f66dc1ef09409133789b3763/xsl/xml2tex.xsl#L59) and [line 65](https://github.com/transpect/xml2tex/blob/82cd2ad06a7bc2b8f66dc1ef09409133789b3763/xsl/xml2tex.xsl#L65).

.
