### ISSUE TITLE
Space after formula

### ISSUE THREAD

**Issue by BravoBaldo** [transpect/docx2tex#86]
In a docx I wrote 3 rows:
fractions are 7/80=0.90, 25/80=0.31 and 51/80=0.64, continue the text

fractions are 7/80 = 0.90, 25/80 = 0.31 e 51/80 = 0.64, text continue

each 7/80 = 0.90, bla bla

1) I don't know why but only the first two lines are treated as a formula like
2) A space was added after 'formulas and before commas:

....
\begin{document}
fractions are  $7/80=0.90$ ,  $25/80=0.31$  and  $51/80=0.64$ , continue the text

fractions are  $7/80 = 0.90$ ,  $25/80 = 0.31$  e  $51/80 = 0.64$ , text continue

each 7/80 = 0.90, bla bla

\end{document}
....

**Comment by gimsieke** [comment]
We need to see a docx file that contains the content that you cited above. Maybe you can prepare a minimal example that lets us reproduce the behavior.

**Comment by mkraetke** [comment]
@BravoBaldo: If you want your equations completely in math mode, I would suggest that you use the MS Word equation editor or MathType to insert your formulas. Otherwise docx2tex provides only a few heuristics based on some text patterns which detect equation-like expressions in the text and set them in math mode.

**Comment by BravoBaldo** [comment]
[BugSample.docx](https://github.com/transpect/docx2tex/files/6379665/BugSample.docx)

You are not always in control of the docx file!
In this case it is not a true 'formula'

**Comment by BravoBaldo** [comment]
the true project is on github: https://github.com/BravoBaldo/IntroToSignalProcessing_it
In any case the space after between th 'formula' and the comma... is strange

**Comment by mkraetke** [comment]
The space before and after the detected text equations are now removed and the math environment is applied to the last equation:

```tex
fractions are $7/80=0.90$, $25/80=0.31$ and $51/80=0.64$, continue the text

fractions are $7/80 = 0.90$, $25/80 = 0.31$ e $51/80 = 0.64$, text continue

each $7/80 = 0.90$, bla bla
```
