### ISSUE TITLE
Incomplete heuristics for 'formula'

### ISSUE THREAD

**Issue by BravoBaldo** [transpect/docx2tex#87]
[ans.docx](https://github.com/transpect/docx2tex/files/6448007/ans.docx)
The simple line "ans = 1.0000  -0.5000-0.8660i  -0.5000+0.8660i" is interpretedd as a formula, correctly, but 

1) the last 'i' was not considered as part of the formula
2) 'ans' was not considered a whole variable

\texttt{an$s = 1.0000 -0.5000-0.8660$$i -0.5000+0.8660$i}

P.S.: Thanks for sharing your great software

**Comment by gimsieke** [comment]
As @mkraetke wrote in https://github.com/transpect/docx2tex/issues/86#issuecomment-827063683, it is recommended that you use equations proper (preferably OMML, that is, the Word-native equations of Office 2007 and later) to typeset equations. Martin might improve the heuristics for trailing upright letters such as i and e, but I think this is a piecemeal fix that will inevitably fail for other people’s plain-text formulas. Improving the heuristics will raise users’ expectations that every such formula will be recognized properly while we, on the contrary, tend to encourage users to use proper equations for, um, equations.

**Comment by BravoBaldo** [comment]
the line in question may NOT be a formula at all, but if the program senses it is, it will process it completely.

by the way, at the moment the latest version downloaded from git is unstable:
[OutIntroToSignalProcessing2021.log](https://github.com/transpect/docx2tex/files/6468213/OutIntroToSignalProcessing2021.log)

**Comment by mkraetke** [comment]
The issue with the conversion error in the master branch is fixed. The other reported issue will not be fixed. Sure, there can be some heuristics implemented which detect more equations. However, more heuristics increase the risk of ambiguous matches, too. Plus, no of our customers asked for it and would pay for this. So I'm afraid you have to write the editions in the equation editor and not as regular text in MS Word.
