### ISSUE TITLE
run with windows  

### ISSUE THREAD

**Issue by wudeman** [transpect/docx2tex#89]
FATAL: Failed to parse Saxon configuration file.
java.nio.file.InvalidPathException: Illegal char <*> at index 67: C:\docx2tex\calabash\extensions\transpect\javascript-extension\lib\*

**Comment by gimsieke** [comment]
How exactly is your invocation, and from which directory using which shell (maybe cmd)?

**Comment by wudeman** [comment]
C:\docx2tex>d2t.bat C:\qct\uploadPaper\test\2012年海南省高考数学压轴卷（文科）.docx
starting docx2tex
Errors encountered while running docx2tex. Please see C:/qct/uploadPaper/test/2012年海南省高考数学压轴卷（文科）.log for details.

**Comment by wudeman** [comment]
with cmd

**Comment by wudeman** [comment]
My java version is 11, maybe it's the influence of java version?

**Comment by gimsieke** [comment]
Can you attach the log file? 
I think it’s possible that we haven’t fully taught the Windows .bat invocation to treat spaces in file or directory names correctly. Can you try it once more after renaming the input?

**Comment by wudeman** [comment]
> Can you attach the log [file?](url)
> I think it’s possible that we haven’t fully taught the Windows .bat invocation to treat spaces in file or directory names correctly. Can you try it once more after renaming the input?

**Comment by wudeman** [comment]
> Can you attach the log file?
> I think it’s possible that we haven’t fully taught the Windows .bat invocation to treat spaces in file or directory names correctly. Can you try it once more after renaming the input?
If you use the CMD command to execute, the Chinese file name will be garbled. How to solve this problem? The log information is as follows:

INFO : xpl/docx2tex. xpl:197 :38:No custom-font-maps loaded.

[ERROR] Unzip: D:\Test\2012�� ѧ. Docx (the system cannot find the specified file.)

ERROR: step p:xslt named zip-manifest at file:/D:/docx2tex/docx2hub/xpl/single-tree. xpl:160 :docx2hub/xpl/single-tree. xpl:160 :58:p:xslt returned non-XML result

ERROR: step p:xslt named zip-manifest at file:/D:/docx2tex/docx2hub/xpl/single-tree. xpl:160 :docx2hub/xpl/single-tree. xpl:160 :58:p:xslt returned non-XML result

ERROR: step p:xslt named zip-manifest at file:/D:/docx2tex/docx2hub/xpl/single-tree. xpl:160 :docx2hub/xpl/single-tree. xpl:160 :58:p:xslt returned non-XML result

ERROR: step p:xslt named zip-manifest at file:/D:/docx2tex/docx2hub/xpl/single-tree. xpl:160 :docx2hub/xpl/single-tree. xpl:160 :58:p:xslt returned non-XML result

ERROR: p:xslt returned non-XML result

**Comment by gimsieke** [comment]
`2012�� ѧ. Docx` looks like the encoding of the file name or of Windows are not properly recognized.

What codepage does `chcp` report? It should be 65001 (UTF-8).

You might need to activate UTF-8 as system locale:

https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#cite_note-15

I’ve experimented quite a bit with UTF-8 support in Java on Windows: https://stackoverflow.com/questions/7660651/passing-command-line-unicode-argument-to-java-code#comments-link-9043883

Regarding your first comment:

> FATAL: Failed to parse Saxon configuration file.
> java.nio.file.InvalidPathException: Illegal char <*> at index 67: C:\docx2tex\calabash\extensions\transpect\javascript-extension\lib*

I just saw it, it escaped my attention when I wrote the first reply. I don’t know why the path ends with `lib*`. I can only see this line in calabash/calabash.bat:

`@set javascriptext=%extensions%transpect/javascript-extension;%extensions%transpect/javascript-extension/lib/*`

So there is a slash in front of the asterisk.

But I remember that Java 11 has a file URI (and maybe also file OS path) bug. You can try whether it works better with Java 8 or Java 13 or newer.

Or did you alter calabash.bat yourself?

**Comment by wudeman** [comment]
Thank you for your reply. I'll try again
