### ISSUE TITLE
conf.csv in d2t

### ISSUE THREAD

**Issue by gimsieke** [transpect/docx2tex#9]
Why is there a default value of [conf.csv](https://github.com/transpect/docx2tex/blame/master/d2t#L106) when the pipeline actually expects an XML file (that it then loads with tr:load)?

**Comment by gimsieke** [comment]
Changed this in fb7830f

**Comment by mkraetke** [comment]
If the CSV file could not be loaded for any reason, then always the XML file is loaded as fallback.

**Comment by mkraetke** [comment]
The CSV file is parsed will be converted to an xml2tex file. This is done here: https://github.com/transpect/docx2tex/blob/master/xsl/convert-config.xsl
