### ISSUE TITLE
Can I control which files are exported？

### ISSUE THREAD

**Issue by benzxiaojunjun** [transpect/docx2tex#90]
![image](https://user-images.githubusercontent.com/72971361/121456493-bfa03a80-c9d8-11eb-9014-8e7a796accf6.png)
How can I output only TeX files and media files？This may improve the output speed.

**Comment by gimsieke** [comment]
I doubt that it will speed things up. One would need to analyze what takes so long. We can do this, but we need your input file. One candidate is [MathType formulas](https://github.com/transpect/mathtype-extension/issues/18). And there is a general overhead for starting the JVM, invoking the processor, compiling the stylesheets, and applying all conversion steps to even a small input file. This overhead may be in the order of 20 seconds, depending on your computer’s performance. If you invoked it with `d2t.bat`, debugging seems to switched on unconditionally. It will store some (many) files in `test.debug` then. The non-Windows script, `d2t`, has a switch to enable debugging which is disabled by default there. You can edit `d2t.bat` and change `debug=yes` to `debug=no`. But as I said, I doubt that it will have a significant effect unless your storage is very slow.

**Comment by benzxiaojunjun** [comment]
https://user-images.githubusercontent.com/72971361/121481608-e1141d00-c9fe-11eb-9b2d-12dd758c3cb6.mp4
Here is my input file:
[test.docx](https://github.com/transpect/docx2tex/files/6629138/test.docx)
From the recording screen, we can see that I use **dat** and set **DEBUG=no**, but still have the **debug folder** output. Moreover, **debug folder** and **csv** file consume a lot of time. Can we add parameters to control whether to output unnecessary files such as **csv** and **xml**? Because I think most people only need TeX file, which is just my personal opinion.

**Comment by gimsieke** [comment]
Thanks for the screencast, which gave me an impression of the speed. I wouldn’t consider this slow. As I said, that’s the overhead to expect. Omitting files for output won’t help. I will check, but I also think that even if the debug dir is created, it will contain only very few files about the progress of the conversion.

**Comment by gimsieke** [comment]
I invoked it myself and can confirm that test.debug only contains a subdir 'status' with 12 small text files in it. Producing these and the other files such as test.csv, test.d2t.log, and test.xml consumes virtually no time. The overhead is as it is, there is nothing we can do. You will see if you convert larger file that the time needed will increase far less than proportional to the page count.
