### ISSUE TITLE
Mexican Spanish

### ISSUE THREAD

**Issue by skinkie** [transpect/docx2tex#92]
The translation from British English and Mexican Spanish gives broken LaTeX output.

Foreign language looks like: 
```tex
\foreignlanguage{spanish,mexico}{Margarita}
```

But worse the babel usepackage is not able to import in this way:
```text
\usepackage[swedish,english,british,spanish,mexico,spanish,latin,english,dutch]{babel}
```

**Comment by mkraetke** [comment]
Hi Stefan,

thank you for the report. Can you just send me the docx file which caused the issue?

best, Martin

**Comment by skinkie** [comment]
[talentest.docx](https://github.com/transpect/docx2tex/files/6840109/talentest.docx)

**Comment by mkraetke** [comment]
You need to update docx2tex and the submodule xml2tex as well. If Mexican Spanish is detected, then this will be the babel declaration:

```diff
+ \def\spanishoptions{mexico}
+ \usepackage[spanish,]{babel}
- \usepackage[spanish,mexico]{babel}
```

`\foreignlanguage` has only Spanish as parameter. 

```diff
+ \foreignlanguage{spanish}{Tequila}
- \foreignlanguage{spanish,mexico}{Tequila}
```

I don't think this will work for authors who want to switch between Mexican and Castilian Spanish in one document. Presumably, this is rarely the case.

**Comment by skinkie** [comment]
But I think the case of switching between American English and British English would be something valuable.

**Comment by mkraetke** [comment]
This is already implemented: docx2tex switches with `\foreignlanguage{english}` and `\foreignlanguage{british}` between American and British English.
