### ISSUE TITLE
"A sequence of more than one item is not allowed as the third argument of fn:concat()" while  conversion from docx

### ISSUE THREAD

**Issue by Atif20024** [transpect/docx2tex#93]
Message: A sequence of more than one item is not allowed as the third argument of fn:concat() (1, 2) 
Message: [FATAL ERROR]: XSLT mode 'xml2tex' failed due to conversion errors. 
ERROR: xproc-util/xslt-mode/xpl/xslt-mode.xpl:0:xslt-mode-xml2tex:[EL11P104.d2t.log](https://github.com/transpect/docx2tex/files/7007157/EL11P104.d2t.log) (1, 2) 
ERROR: xproc-util/xslt-mode/xpl/xslt-mode.xpl:0:xslt-mode-xml2tex:A sequence of more than one item is not allowed as the third argument of fn:concat() (1, 2) 
ERROR: xproc-util/xslt-mode/xpl/xslt-mode.xpl:0:xslt-mode-xml2tex:A sequence of more than one item is not allowed as the third argument of fn:concat() (1, 2) 
ERROR: Unknown error
[EL11P104.d2t.log](https://github.com/transpect/docx2tex/files/7007164/EL11P104.d2t.log)

P.S: the log file is attached.

**Comment by gimsieke** [comment]
It will help us diagnose the issue if you send us the docx file. If you don’t want to attach it to this issue, you can send it to letexml at le-tex dot de.

**Comment by Atif20024** [comment]
[EL12P013_DC_Part 2.docx](https://github.com/transpect/docx2tex/files/7012184/EL12P013_DC_Part.2.docx)

Hi, I have already mailed the file to the given email address. Here is another file, that gives me the same issue.
(heap size used: 2048m)

**Comment by mkraetke** [comment]
If you pull the master branch, the fix referenced above fixes your issue.

**Comment by Atif20024** [comment]
It seems to run fine now. Thank you @mkraetke @gimsieke for the support.

**Comment by gimsieke** [comment]
Thanks for your feedback and thanks for reporting the issue in the first place. Users like you help us improve the converter, one tiny bug at a time.
