### ISSUE TITLE
Could not load file:/mnt/c/docx2tex/conf/conf.csv

### ISSUE THREAD

**Issue by wudeman** [transpect/docx2tex#95]
Hello @mkraetke ,I encountered the following problems when converting documents. I don't know what caused them. Can you help me have a look? Thank you very much!
cp: './data/file/paper/1634122442705/2022届高考物理一轮复习单元训练：相互作用.docx' and '/mnt/c/qct/uploadPaper/test/data/file/paper/1634122442705/2022届高考物理一轮复习单元训练：相互作用.docx' are the same file
INFO : file:/mnt/c/docx2tex/xpl/docx2tex.xpl:197:38:No custom-font-maps loaded.
ERROR: file:///mnt/c/docx2tex/xproc-util/load/xpl/load.xpl:0:load-error:Could not load file:/mnt/c/docx2tex/conf/conf.csv (file:///mnt/c/docx2tex/xproc-util/load/xpl/load.xpl) dtd-validate=false
ERROR: file:///mnt/c/docx2tex/xproc-util/load/xpl/load.xpl:0:load-error:Could not load file:/mnt/c/docx2tex/conf/conf.csv (file:///mnt/c/docx2tex/xproc-util/load/xpl/load.xpl) dtd-validate=false
WARN : file:///mnt/c/docx2tex/docx2hub/xsl/main.xsl:80:7:err:XTSE0090:Unrecognized attribute in Saxon namespace: saxon:suppress-indentation
WARN : file:/mnt/c/docx2tex/docx2hub/xsl/numbering.xsl:157:92:err:SXWN9011:Memo functions are not available in Saxon-HE: saxon:memo-function attribute ignored
Message: Mode: insert-xpath
Message: Mode: insert-doc-defaults
unsupported Java version "11", defaulting to 1.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil (file:/mnt/c/docx2tex/calabash/extensions/transpect/mathtype-extension/lib/jruby-complete-9.1.8.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Message: Mode: docx2hub:resolve-tblBorders
Message: Mode: docx2hub:add-props
Message: An empty sequence is not allowed as the value of variable $marginTop
Message: [FATAL ERROR]: XSLT mode 'docx2hub:add-props' failed due to conversion errors. Recovering from errors and proceeding with original input. 
Message: Mode: docx2hub:props2atts
Message: Mode: docx2hub:remove-redundant-run-atts
Message: Mode: docx2hub:join-instrText-runs
Message: No value supplied for required parameter $nested-fldChars. A value is required because the default value is not a valid instance of the required type
Message: [FATAL ERROR]: XSLT mode 'docx2hub:join-instrText-runs' failed due to conversion errors. Recovering from errors and proceeding with original input. 
ERROR: err:XD0003:XD0003
ERROR: err:XD0003:XD0003
ERROR: It is a dynamic error if the viewport source does not provide exactly one document.
[2022届高考物理一轮复习单元训练：相互作用.docx](https://github.com/transpect/docx2tex/files/7337605/2022.docx)

**Comment by mkraetke** [comment]
Thanks for your report. I'll check the docx file.

**Comment by mkraetke** [comment]
Should be fixed with the [current v1.7 release ](https://github.com/transpect/docx2tex/releases/tag/v.1.7).
