### ISSUE TITLE
Issues in Overset and Double Exponents

### ISSUE THREAD

**Issue by sathishvelu2020** [transpect/docx2tex#96]
Issue 1: Overset Rule should be expanded, has to be changed to double overline - Equation 1
Issue2: Double exponent Issues, where we have latex error - Equation 2

Both the equations are attached in the document
[Transpect.docx](https://github.com/transpect/docx2tex/files/7698162/Transpect.docx)

**Comment by mkraetke** [comment]
I've fixed both issues. Please get the latest [1.7.1 release](https://github.com/transpect/docx2tex/releases/tag/v.1.7.1). This release does not only resolve this issue but also close the log4j vulnerability everybody is talking about.
