### ISSUE TITLE
Is it possible to change the inline math delimiter?

### ISSUE THREAD

**Issue by mjr** [transpect/docx2tex#98]
The image below shows 3 latex options for inline math delimiter, is it possible to pass a parameter to define which one to use?

<img width="624" alt="Screen Shot 2022-09-12 at 20 53 06" src="https://user-images.githubusercontent.com/9324986/189778374-9028e510-5431-4de0-9426-3d3e27069d7b.png">

Image ref: https://www.overleaf.com/learn/latex/Mathematical_expressions#Inline_math_mode

**Comment by mkraetke** [comment]
It's a possible but a bit more complicated since some mappings in our character map contain already Dollar characters. Unfortunately, I'm very busy at the moment, so I cannot give you a time frame for resolving this issue.

**Comment by mjr** [comment]
@mkraetke Would it be simpler if I made a fork and replaced the character map of `$` with `$$` or something similar?

I'm wanting to do this because I'm wanting to identify where there are inline formulas, but it gets more complicated because the dollar might not be a formula. (ex: `$500, $400`)

**Comment by mkraetke** [comment]
Perhaps it's not necessary to fork the entire project. You can just create your own configuration and import the [docx2tex configuration](https://github.com/transpect/docx2tex/blob/master/conf/conf.xml). Then you could just overwrite the things you don't like and use the command line parameter `-c` to pass the path to your custom configuration. Here is a sample configuration that would be sufficient:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<set xmlns="http://transpect.io/xml2tex"  
     xmlns:tr="http://transpect.io"
     xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  
  <import href="docx2tex/conf/conf.xml"/>
  
  <!-- override lines 742 to 749 of docx2tex/conf/conf.xml
       applies to real Word equations which are treated by 
       our mml2tex module -->

  <template context="dbk:inlineequation[not(ancestor::dbk:superscript or ancestor::dbk:subscript )]
                    |dbk:equation[ancestor::dbk:table or ancestor::dbk:informaltable]">
    <rule>
      <text select="'\begin{math}'"/>
      <text/>
      <text select="'\end{math}'"/>
    </rule>
  </template>
  
  <!-- selectively override the character mappings. Please 
       note that this apply to text characters outside of equations. -->
  
  <charmap ignore-imported-charmaps="false">
    <!--DEGREE SIGN -->
    <char character="&#xb0;" string="\begin{math}\circ\end{math}"/>
  </charmap>
  
</set>
```

**Comment by mjr** [comment]
@mkraetke Thank you very much, it worked perfectly.
