### ISSUE TITLE
Convert to LaTeX only math formulas and the like

### ISSUE THREAD

**Issue by franklindias** [transpect/docx2tex#99]
@gimsieke  @mkraetke thank you very much for maintaining this repository it has already helped us a lot in our project.

I have the following challenge: I need only mathematical formulas and the like to be converted into latex and the other texts and images ideally in html, but it could be in normal text if that's the case.

Do you have any idea how I can do this?

thank you so much

**Comment by mkraetke** [comment]
Hi @franklindias,

sorry for the late reply but we were busy with our transpect user group which took place on past Friday in Leipzig. The easiest way would be to add `-d` on the command line to switch debugging output on. After the conversion, just have a look into `myFile.debug/xml2tex/20.mml2tex.xml`. This document contains a DocBook XML document but the MathML equations are already replaced with TeX encapsulated in XML processing instructions.

From there on, you can take the Norman Tovey-Walsh's [DocBook XSLT stylesheets](https://github.com/docbook/xslTNG), adjust it to your needs and convert HTML from the DocBook document.

Kind regards,
Martin

**Comment by franklindias** [comment]
Thank you so much @mkraetke , it will help us a lot.
